//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class eTrainingScheduleEntities : DbContext
    {
        public eTrainingScheduleEntities()
            : base("name=eTrainingScheduleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Account> tbl_Account { get; set; }
        public virtual DbSet<tbl_FeaId> tbl_FeaId { get; set; }
        public virtual DbSet<tbl_Permisstion> tbl_Permisstion { get; set; }
        public virtual DbSet<tbl_Role> tbl_Role { get; set; }
        public virtual DbSet<tbl_S07_Courses> tbl_S07_Courses { get; set; }
        public virtual DbSet<tbl_S07_CoursesJournal> tbl_S07_CoursesJournal { get; set; }
        public virtual DbSet<tbl_S07_CoursesStudentDetailt> tbl_S07_CoursesStudentDetailt { get; set; }
        public virtual DbSet<tbl_S07_Experts> tbl_S07_Experts { get; set; }
        public virtual DbSet<tbl_S07_ExpertsDetailt> tbl_S07_ExpertsDetailt { get; set; }
        public virtual DbSet<tbl_S07_Schedulers> tbl_S07_Schedulers { get; set; }
        public virtual DbSet<tbl_S07_ShiftDay> tbl_S07_ShiftDay { get; set; }
        public virtual DbSet<tbl_S07_Student> tbl_S07_Student { get; set; }
        public virtual DbSet<tbl_S07_StudentDetailt> tbl_S07_StudentDetailt { get; set; }
        public virtual DbSet<tbl_S07_Weekdays> tbl_S07_Weekdays { get; set; }
    
        public virtual ObjectResult<CoursesStudentDetail_Join_Result> CoursesStudentDetail_Join()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CoursesStudentDetail_Join_Result>("CoursesStudentDetail_Join");
        }
    
        public virtual ObjectResult<sp_Account_CheckLogin_Result> sp_Account_CheckLogin(string username, string passWord)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passWordParameter = passWord != null ?
                new ObjectParameter("PassWord", passWord) :
                new ObjectParameter("PassWord", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Account_CheckLogin_Result>("sp_Account_CheckLogin", usernameParameter, passWordParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual ObjectResult<sp_CoursesJournal_Join_Result> sp_CoursesJournal_Join()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CoursesJournal_Join_Result>("sp_CoursesJournal_Join");
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_ExpertsDetailt_Join_Result> sp_ExpertsDetailt_Join()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ExpertsDetailt_Join_Result>("sp_ExpertsDetailt_Join");
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<sp_Schedulers_Join_Result> sp_Schedulers_Join()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Schedulers_Join_Result>("sp_Schedulers_Join");
        }
    
        public virtual ObjectResult<sp_StudentDetailt_Join_Result> sp_StudentDetailt_Join()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_StudentDetailt_Join_Result>("sp_StudentDetailt_Join");
        }
    
        public virtual int sp_tbl_Account_DELETE(Nullable<System.Guid> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_Account_DELETE", userIdParameter);
        }
    
        public virtual ObjectResult<sp_tbl_Account_GetAll_Result> sp_tbl_Account_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tbl_Account_GetAll_Result>("sp_tbl_Account_GetAll");
        }
    
        public virtual ObjectResult<sp_tbl_Account_GetByUserId_Result> sp_tbl_Account_GetByUserId(Nullable<System.Guid> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tbl_Account_GetByUserId_Result>("sp_tbl_Account_GetByUserId", userIdParameter);
        }
    
        public virtual int sp_tbl_Account_INSERT(Nullable<System.Guid> userId, string fullName, string passWord, string username, string email, string phone, string description, Nullable<bool> isdeleted, Nullable<System.Guid> roleId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(System.Guid));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var passWordParameter = passWord != null ?
                new ObjectParameter("PassWord", passWord) :
                new ObjectParameter("PassWord", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var isdeletedParameter = isdeleted.HasValue ?
                new ObjectParameter("Isdeleted", isdeleted) :
                new ObjectParameter("Isdeleted", typeof(bool));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_Account_INSERT", userIdParameter, fullNameParameter, passWordParameter, usernameParameter, emailParameter, phoneParameter, descriptionParameter, isdeletedParameter, roleIdParameter);
        }
    
        public virtual int sp_tbl_Account_UPDATE(Nullable<System.Guid> userId, string fullName, string passWord, string username, string email, string phone, string description, Nullable<bool> isdeleted, Nullable<System.Guid> roleId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(System.Guid));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var passWordParameter = passWord != null ?
                new ObjectParameter("PassWord", passWord) :
                new ObjectParameter("PassWord", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var isdeletedParameter = isdeleted.HasValue ?
                new ObjectParameter("Isdeleted", isdeleted) :
                new ObjectParameter("Isdeleted", typeof(bool));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_Account_UPDATE", userIdParameter, fullNameParameter, passWordParameter, usernameParameter, emailParameter, phoneParameter, descriptionParameter, isdeletedParameter, roleIdParameter);
        }
    
        public virtual int sp_tbl_FeaId_DELETE(string feaId)
        {
            var feaIdParameter = feaId != null ?
                new ObjectParameter("FeaId", feaId) :
                new ObjectParameter("FeaId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_FeaId_DELETE", feaIdParameter);
        }
    
        public virtual ObjectResult<sp_tbl_FeaId_GetAll_Result> sp_tbl_FeaId_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tbl_FeaId_GetAll_Result>("sp_tbl_FeaId_GetAll");
        }
    
        public virtual ObjectResult<sp_tbl_FeaId_GetByFeaId_Result> sp_tbl_FeaId_GetByFeaId(string feaId)
        {
            var feaIdParameter = feaId != null ?
                new ObjectParameter("FeaId", feaId) :
                new ObjectParameter("FeaId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tbl_FeaId_GetByFeaId_Result>("sp_tbl_FeaId_GetByFeaId", feaIdParameter);
        }
    
        public virtual int sp_tbl_FeaId_INSERT(string feaId, string feaName, Nullable<bool> isdeleted)
        {
            var feaIdParameter = feaId != null ?
                new ObjectParameter("FeaId", feaId) :
                new ObjectParameter("FeaId", typeof(string));
    
            var feaNameParameter = feaName != null ?
                new ObjectParameter("FeaName", feaName) :
                new ObjectParameter("FeaName", typeof(string));
    
            var isdeletedParameter = isdeleted.HasValue ?
                new ObjectParameter("Isdeleted", isdeleted) :
                new ObjectParameter("Isdeleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_FeaId_INSERT", feaIdParameter, feaNameParameter, isdeletedParameter);
        }
    
        public virtual int sp_tbl_FeaId_UPDATE(string feaId, string feaName, Nullable<bool> isdeleted)
        {
            var feaIdParameter = feaId != null ?
                new ObjectParameter("FeaId", feaId) :
                new ObjectParameter("FeaId", typeof(string));
    
            var feaNameParameter = feaName != null ?
                new ObjectParameter("FeaName", feaName) :
                new ObjectParameter("FeaName", typeof(string));
    
            var isdeletedParameter = isdeleted.HasValue ?
                new ObjectParameter("Isdeleted", isdeleted) :
                new ObjectParameter("Isdeleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_FeaId_UPDATE", feaIdParameter, feaNameParameter, isdeletedParameter);
        }
    
        public virtual int sp_tbl_Permisstion_DELETE(Nullable<System.Guid> perID)
        {
            var perIDParameter = perID.HasValue ?
                new ObjectParameter("PerID", perID) :
                new ObjectParameter("PerID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_Permisstion_DELETE", perIDParameter);
        }
    
        public virtual ObjectResult<sp_tbl_Permisstion_GetAll_Result> sp_tbl_Permisstion_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tbl_Permisstion_GetAll_Result>("sp_tbl_Permisstion_GetAll");
        }
    
        public virtual ObjectResult<sp_tbl_Permisstion_GetByPerID_Result> sp_tbl_Permisstion_GetByPerID(Nullable<System.Guid> perID)
        {
            var perIDParameter = perID.HasValue ?
                new ObjectParameter("PerID", perID) :
                new ObjectParameter("PerID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tbl_Permisstion_GetByPerID_Result>("sp_tbl_Permisstion_GetByPerID", perIDParameter);
        }
    
        public virtual int sp_tbl_Permisstion_INSERT(Nullable<System.Guid> perID, Nullable<bool> f_ADD, Nullable<bool> f_EDIT, Nullable<bool> f_DELETE, Nullable<bool> f_SEARCH, string feaId, Nullable<System.Guid> userId)
        {
            var perIDParameter = perID.HasValue ?
                new ObjectParameter("PerID", perID) :
                new ObjectParameter("PerID", typeof(System.Guid));
    
            var f_ADDParameter = f_ADD.HasValue ?
                new ObjectParameter("F_ADD", f_ADD) :
                new ObjectParameter("F_ADD", typeof(bool));
    
            var f_EDITParameter = f_EDIT.HasValue ?
                new ObjectParameter("F_EDIT", f_EDIT) :
                new ObjectParameter("F_EDIT", typeof(bool));
    
            var f_DELETEParameter = f_DELETE.HasValue ?
                new ObjectParameter("F_DELETE", f_DELETE) :
                new ObjectParameter("F_DELETE", typeof(bool));
    
            var f_SEARCHParameter = f_SEARCH.HasValue ?
                new ObjectParameter("F_SEARCH", f_SEARCH) :
                new ObjectParameter("F_SEARCH", typeof(bool));
    
            var feaIdParameter = feaId != null ?
                new ObjectParameter("FeaId", feaId) :
                new ObjectParameter("FeaId", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_Permisstion_INSERT", perIDParameter, f_ADDParameter, f_EDITParameter, f_DELETEParameter, f_SEARCHParameter, feaIdParameter, userIdParameter);
        }
    
        public virtual int sp_tbl_Permisstion_UPDATE(Nullable<System.Guid> perID, Nullable<bool> f_ADD, Nullable<bool> f_EDIT, Nullable<bool> f_DELETE, Nullable<bool> f_SEARCH, string feaId, Nullable<System.Guid> userId)
        {
            var perIDParameter = perID.HasValue ?
                new ObjectParameter("PerID", perID) :
                new ObjectParameter("PerID", typeof(System.Guid));
    
            var f_ADDParameter = f_ADD.HasValue ?
                new ObjectParameter("F_ADD", f_ADD) :
                new ObjectParameter("F_ADD", typeof(bool));
    
            var f_EDITParameter = f_EDIT.HasValue ?
                new ObjectParameter("F_EDIT", f_EDIT) :
                new ObjectParameter("F_EDIT", typeof(bool));
    
            var f_DELETEParameter = f_DELETE.HasValue ?
                new ObjectParameter("F_DELETE", f_DELETE) :
                new ObjectParameter("F_DELETE", typeof(bool));
    
            var f_SEARCHParameter = f_SEARCH.HasValue ?
                new ObjectParameter("F_SEARCH", f_SEARCH) :
                new ObjectParameter("F_SEARCH", typeof(bool));
    
            var feaIdParameter = feaId != null ?
                new ObjectParameter("FeaId", feaId) :
                new ObjectParameter("FeaId", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_Permisstion_UPDATE", perIDParameter, f_ADDParameter, f_EDITParameter, f_DELETEParameter, f_SEARCHParameter, feaIdParameter, userIdParameter);
        }
    
        public virtual int sp_tbl_Role_DELETE(Nullable<System.Guid> roleId)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_Role_DELETE", roleIdParameter);
        }
    
        public virtual ObjectResult<sp_tbl_Role_GetAll_Result> sp_tbl_Role_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tbl_Role_GetAll_Result>("sp_tbl_Role_GetAll");
        }
    
        public virtual ObjectResult<sp_tbl_Role_GetByRoleId_Result> sp_tbl_Role_GetByRoleId(Nullable<System.Guid> roleId)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tbl_Role_GetByRoleId_Result>("sp_tbl_Role_GetByRoleId", roleIdParameter);
        }
    
        public virtual int sp_tbl_Role_INSERT(Nullable<System.Guid> roleId, string rName, Nullable<bool> isdeleted)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(System.Guid));
    
            var rNameParameter = rName != null ?
                new ObjectParameter("RName", rName) :
                new ObjectParameter("RName", typeof(string));
    
            var isdeletedParameter = isdeleted.HasValue ?
                new ObjectParameter("Isdeleted", isdeleted) :
                new ObjectParameter("Isdeleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_Role_INSERT", roleIdParameter, rNameParameter, isdeletedParameter);
        }
    
        public virtual int sp_tbl_Role_UPDATE(Nullable<System.Guid> roleId, string rName, Nullable<bool> isdeleted)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(System.Guid));
    
            var rNameParameter = rName != null ?
                new ObjectParameter("RName", rName) :
                new ObjectParameter("RName", typeof(string));
    
            var isdeletedParameter = isdeleted.HasValue ?
                new ObjectParameter("Isdeleted", isdeleted) :
                new ObjectParameter("Isdeleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_Role_UPDATE", roleIdParameter, rNameParameter, isdeletedParameter);
        }
    
        public virtual int sp_tbl_S07_Courses_DELETE(Nullable<System.Guid> coId)
        {
            var coIdParameter = coId.HasValue ?
                new ObjectParameter("CoId", coId) :
                new ObjectParameter("CoId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_S07_Courses_DELETE", coIdParameter);
        }
    
        public virtual ObjectResult<sp_tbl_S07_Courses_GetAll_Result> sp_tbl_S07_Courses_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tbl_S07_Courses_GetAll_Result>("sp_tbl_S07_Courses_GetAll");
        }
    
        public virtual ObjectResult<sp_tbl_S07_Courses_GetByCoId_Result> sp_tbl_S07_Courses_GetByCoId(Nullable<System.Guid> coId)
        {
            var coIdParameter = coId.HasValue ?
                new ObjectParameter("CoId", coId) :
                new ObjectParameter("CoId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tbl_S07_Courses_GetByCoId_Result>("sp_tbl_S07_Courses_GetByCoId", coIdParameter);
        }
    
        public virtual int sp_tbl_S07_Courses_INSERT(Nullable<System.Guid> coId, string courseId, string courseName, Nullable<byte> totalNumber, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<bool> status, string description, Nullable<bool> deleted)
        {
            var coIdParameter = coId.HasValue ?
                new ObjectParameter("CoId", coId) :
                new ObjectParameter("CoId", typeof(System.Guid));
    
            var courseIdParameter = courseId != null ?
                new ObjectParameter("CourseId", courseId) :
                new ObjectParameter("CourseId", typeof(string));
    
            var courseNameParameter = courseName != null ?
                new ObjectParameter("CourseName", courseName) :
                new ObjectParameter("CourseName", typeof(string));
    
            var totalNumberParameter = totalNumber.HasValue ?
                new ObjectParameter("TotalNumber", totalNumber) :
                new ObjectParameter("TotalNumber", typeof(byte));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var deletedParameter = deleted.HasValue ?
                new ObjectParameter("Deleted", deleted) :
                new ObjectParameter("Deleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_S07_Courses_INSERT", coIdParameter, courseIdParameter, courseNameParameter, totalNumberParameter, startDateParameter, endDateParameter, statusParameter, descriptionParameter, deletedParameter);
        }
    
        public virtual int sp_tbl_S07_Courses_UPDATE(Nullable<System.Guid> coId, string courseId, string courseName, Nullable<byte> totalNumber, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<bool> status, string description, Nullable<bool> deleted)
        {
            var coIdParameter = coId.HasValue ?
                new ObjectParameter("CoId", coId) :
                new ObjectParameter("CoId", typeof(System.Guid));
    
            var courseIdParameter = courseId != null ?
                new ObjectParameter("CourseId", courseId) :
                new ObjectParameter("CourseId", typeof(string));
    
            var courseNameParameter = courseName != null ?
                new ObjectParameter("CourseName", courseName) :
                new ObjectParameter("CourseName", typeof(string));
    
            var totalNumberParameter = totalNumber.HasValue ?
                new ObjectParameter("TotalNumber", totalNumber) :
                new ObjectParameter("TotalNumber", typeof(byte));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var deletedParameter = deleted.HasValue ?
                new ObjectParameter("Deleted", deleted) :
                new ObjectParameter("Deleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_S07_Courses_UPDATE", coIdParameter, courseIdParameter, courseNameParameter, totalNumberParameter, startDateParameter, endDateParameter, statusParameter, descriptionParameter, deletedParameter);
        }
    
        public virtual int sp_tbl_S07_CoursesJournal_DELETE(Nullable<System.Guid> cJId)
        {
            var cJIdParameter = cJId.HasValue ?
                new ObjectParameter("CJId", cJId) :
                new ObjectParameter("CJId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_S07_CoursesJournal_DELETE", cJIdParameter);
        }
    
        public virtual ObjectResult<sp_tbl_S07_CoursesJournal_GetAll_Result> sp_tbl_S07_CoursesJournal_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tbl_S07_CoursesJournal_GetAll_Result>("sp_tbl_S07_CoursesJournal_GetAll");
        }
    
        public virtual ObjectResult<sp_tbl_S07_CoursesJournal_GetByCJId_Result> sp_tbl_S07_CoursesJournal_GetByCJId(Nullable<System.Guid> cJId)
        {
            var cJIdParameter = cJId.HasValue ?
                new ObjectParameter("CJId", cJId) :
                new ObjectParameter("CJId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tbl_S07_CoursesJournal_GetByCJId_Result>("sp_tbl_S07_CoursesJournal_GetByCJId", cJIdParameter);
        }
    
        public virtual int sp_tbl_S07_CoursesJournal_INSERT(Nullable<System.Guid> cJId, Nullable<System.Guid> coId, Nullable<System.DateTime> dayOf, string contents, string description)
        {
            var cJIdParameter = cJId.HasValue ?
                new ObjectParameter("CJId", cJId) :
                new ObjectParameter("CJId", typeof(System.Guid));
    
            var coIdParameter = coId.HasValue ?
                new ObjectParameter("CoId", coId) :
                new ObjectParameter("CoId", typeof(System.Guid));
    
            var dayOfParameter = dayOf.HasValue ?
                new ObjectParameter("DayOf", dayOf) :
                new ObjectParameter("DayOf", typeof(System.DateTime));
    
            var contentsParameter = contents != null ?
                new ObjectParameter("Contents", contents) :
                new ObjectParameter("Contents", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_S07_CoursesJournal_INSERT", cJIdParameter, coIdParameter, dayOfParameter, contentsParameter, descriptionParameter);
        }
    
        public virtual int sp_tbl_S07_CoursesJournal_UPDATE(Nullable<System.Guid> cJId, Nullable<System.Guid> coId, Nullable<System.DateTime> dayOf, string contents, string description)
        {
            var cJIdParameter = cJId.HasValue ?
                new ObjectParameter("CJId", cJId) :
                new ObjectParameter("CJId", typeof(System.Guid));
    
            var coIdParameter = coId.HasValue ?
                new ObjectParameter("CoId", coId) :
                new ObjectParameter("CoId", typeof(System.Guid));
    
            var dayOfParameter = dayOf.HasValue ?
                new ObjectParameter("DayOf", dayOf) :
                new ObjectParameter("DayOf", typeof(System.DateTime));
    
            var contentsParameter = contents != null ?
                new ObjectParameter("Contents", contents) :
                new ObjectParameter("Contents", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_S07_CoursesJournal_UPDATE", cJIdParameter, coIdParameter, dayOfParameter, contentsParameter, descriptionParameter);
        }
    
        public virtual int sp_tbl_S07_CoursesStudentDetailt_Delete(Nullable<System.Guid> scsId)
        {
            var scsIdParameter = scsId.HasValue ?
                new ObjectParameter("ScsId", scsId) :
                new ObjectParameter("ScsId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_S07_CoursesStudentDetailt_Delete", scsIdParameter);
        }
    
        public virtual ObjectResult<sp_tbl_S07_CoursesStudentDetailt_GetAll_Result> sp_tbl_S07_CoursesStudentDetailt_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tbl_S07_CoursesStudentDetailt_GetAll_Result>("sp_tbl_S07_CoursesStudentDetailt_GetAll");
        }
    
        public virtual ObjectResult<sp_tbl_S07_CoursesStudentDetailt_GetByCJId_Result> sp_tbl_S07_CoursesStudentDetailt_GetByCJId(Nullable<System.Guid> cJId)
        {
            var cJIdParameter = cJId.HasValue ?
                new ObjectParameter("CJId", cJId) :
                new ObjectParameter("CJId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tbl_S07_CoursesStudentDetailt_GetByCJId_Result>("sp_tbl_S07_CoursesStudentDetailt_GetByCJId", cJIdParameter);
        }
    
        public virtual ObjectResult<sp_tbl_S07_CoursesStudentDetailt_GetByScsId_Result> sp_tbl_S07_CoursesStudentDetailt_GetByScsId(Nullable<System.Guid> scsId)
        {
            var scsIdParameter = scsId.HasValue ?
                new ObjectParameter("ScsId", scsId) :
                new ObjectParameter("ScsId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tbl_S07_CoursesStudentDetailt_GetByScsId_Result>("sp_tbl_S07_CoursesStudentDetailt_GetByScsId", scsIdParameter);
        }
    
        public virtual ObjectResult<sp_tbl_S07_CoursesStudentDetailt_GetByStudetId_Result> sp_tbl_S07_CoursesStudentDetailt_GetByStudetId(Nullable<System.Guid> studetId)
        {
            var studetIdParameter = studetId.HasValue ?
                new ObjectParameter("StudetId", studetId) :
                new ObjectParameter("StudetId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tbl_S07_CoursesStudentDetailt_GetByStudetId_Result>("sp_tbl_S07_CoursesStudentDetailt_GetByStudetId", studetIdParameter);
        }
    
        public virtual int sp_tbl_S07_CoursesStudentDetailt_INSERT(Nullable<System.Guid> scsId, Nullable<System.Guid> studetId, Nullable<System.Guid> cJId, string description)
        {
            var scsIdParameter = scsId.HasValue ?
                new ObjectParameter("ScsId", scsId) :
                new ObjectParameter("ScsId", typeof(System.Guid));
    
            var studetIdParameter = studetId.HasValue ?
                new ObjectParameter("StudetId", studetId) :
                new ObjectParameter("StudetId", typeof(System.Guid));
    
            var cJIdParameter = cJId.HasValue ?
                new ObjectParameter("CJId", cJId) :
                new ObjectParameter("CJId", typeof(System.Guid));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_S07_CoursesStudentDetailt_INSERT", scsIdParameter, studetIdParameter, cJIdParameter, descriptionParameter);
        }
    
        public virtual int sp_tbl_S07_CoursesStudentDetailt_Update(Nullable<System.Guid> scsId, Nullable<System.Guid> studetId, Nullable<System.Guid> cJId, string description)
        {
            var scsIdParameter = scsId.HasValue ?
                new ObjectParameter("ScsId", scsId) :
                new ObjectParameter("ScsId", typeof(System.Guid));
    
            var studetIdParameter = studetId.HasValue ?
                new ObjectParameter("StudetId", studetId) :
                new ObjectParameter("StudetId", typeof(System.Guid));
    
            var cJIdParameter = cJId.HasValue ?
                new ObjectParameter("CJId", cJId) :
                new ObjectParameter("CJId", typeof(System.Guid));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_S07_CoursesStudentDetailt_Update", scsIdParameter, studetIdParameter, cJIdParameter, descriptionParameter);
        }
    
        public virtual int sp_tbl_S07_Experts_DELETE(Nullable<System.Guid> expertId)
        {
            var expertIdParameter = expertId.HasValue ?
                new ObjectParameter("ExpertId", expertId) :
                new ObjectParameter("ExpertId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_S07_Experts_DELETE", expertIdParameter);
        }
    
        public virtual ObjectResult<sp_tbl_S07_Experts_GetAll_Result> sp_tbl_S07_Experts_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tbl_S07_Experts_GetAll_Result>("sp_tbl_S07_Experts_GetAll");
        }
    
        public virtual ObjectResult<sp_tbl_S07_Experts_GetByExpertId_Result> sp_tbl_S07_Experts_GetByExpertId(Nullable<System.Guid> expertId)
        {
            var expertIdParameter = expertId.HasValue ?
                new ObjectParameter("ExpertId", expertId) :
                new ObjectParameter("ExpertId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tbl_S07_Experts_GetByExpertId_Result>("sp_tbl_S07_Experts_GetByExpertId", expertIdParameter);
        }
    
        public virtual int sp_tbl_S07_Experts_INSERT(Nullable<System.Guid> expertId, string fullName, string email, string mobile, string address, string specialize, Nullable<System.DateTime> startDate, Nullable<bool> status, string description, Nullable<bool> deleted)
        {
            var expertIdParameter = expertId.HasValue ?
                new ObjectParameter("ExpertId", expertId) :
                new ObjectParameter("ExpertId", typeof(System.Guid));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("Mobile", mobile) :
                new ObjectParameter("Mobile", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var specializeParameter = specialize != null ?
                new ObjectParameter("Specialize", specialize) :
                new ObjectParameter("Specialize", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var deletedParameter = deleted.HasValue ?
                new ObjectParameter("Deleted", deleted) :
                new ObjectParameter("Deleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_S07_Experts_INSERT", expertIdParameter, fullNameParameter, emailParameter, mobileParameter, addressParameter, specializeParameter, startDateParameter, statusParameter, descriptionParameter, deletedParameter);
        }
    
        public virtual int sp_tbl_S07_Experts_UPDATE(Nullable<System.Guid> expertId, string fullName, string email, string mobile, string address, string specialize, Nullable<System.DateTime> startDate, Nullable<bool> status, string description, Nullable<bool> deleted)
        {
            var expertIdParameter = expertId.HasValue ?
                new ObjectParameter("ExpertId", expertId) :
                new ObjectParameter("ExpertId", typeof(System.Guid));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("Mobile", mobile) :
                new ObjectParameter("Mobile", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var specializeParameter = specialize != null ?
                new ObjectParameter("Specialize", specialize) :
                new ObjectParameter("Specialize", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var deletedParameter = deleted.HasValue ?
                new ObjectParameter("Deleted", deleted) :
                new ObjectParameter("Deleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_S07_Experts_UPDATE", expertIdParameter, fullNameParameter, emailParameter, mobileParameter, addressParameter, specializeParameter, startDateParameter, statusParameter, descriptionParameter, deletedParameter);
        }
    
        public virtual int sp_tbl_S07_ExpertsDetailt_DELETE(Nullable<System.Guid> exId)
        {
            var exIdParameter = exId.HasValue ?
                new ObjectParameter("ExId", exId) :
                new ObjectParameter("ExId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_S07_ExpertsDetailt_DELETE", exIdParameter);
        }
    
        public virtual ObjectResult<sp_tbl_S07_ExpertsDetailt_GetAll_Result> sp_tbl_S07_ExpertsDetailt_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tbl_S07_ExpertsDetailt_GetAll_Result>("sp_tbl_S07_ExpertsDetailt_GetAll");
        }
    
        public virtual ObjectResult<sp_tbl_S07_ExpertsDetailt_GetByExId_Result> sp_tbl_S07_ExpertsDetailt_GetByExId(Nullable<System.Guid> exId)
        {
            var exIdParameter = exId.HasValue ?
                new ObjectParameter("ExId", exId) :
                new ObjectParameter("ExId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tbl_S07_ExpertsDetailt_GetByExId_Result>("sp_tbl_S07_ExpertsDetailt_GetByExId", exIdParameter);
        }
    
        public virtual int sp_tbl_S07_ExpertsDetailt_INSERT(Nullable<System.Guid> exId, Nullable<System.Guid> expertId, Nullable<System.Guid> coId, string description)
        {
            var exIdParameter = exId.HasValue ?
                new ObjectParameter("ExId", exId) :
                new ObjectParameter("ExId", typeof(System.Guid));
    
            var expertIdParameter = expertId.HasValue ?
                new ObjectParameter("ExpertId", expertId) :
                new ObjectParameter("ExpertId", typeof(System.Guid));
    
            var coIdParameter = coId.HasValue ?
                new ObjectParameter("CoId", coId) :
                new ObjectParameter("CoId", typeof(System.Guid));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_S07_ExpertsDetailt_INSERT", exIdParameter, expertIdParameter, coIdParameter, descriptionParameter);
        }
    
        public virtual int sp_tbl_S07_ExpertsDetailt_UPDATE(Nullable<System.Guid> exId, Nullable<System.Guid> expertId, Nullable<System.Guid> coId, string description)
        {
            var exIdParameter = exId.HasValue ?
                new ObjectParameter("ExId", exId) :
                new ObjectParameter("ExId", typeof(System.Guid));
    
            var expertIdParameter = expertId.HasValue ?
                new ObjectParameter("ExpertId", expertId) :
                new ObjectParameter("ExpertId", typeof(System.Guid));
    
            var coIdParameter = coId.HasValue ?
                new ObjectParameter("CoId", coId) :
                new ObjectParameter("CoId", typeof(System.Guid));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_S07_ExpertsDetailt_UPDATE", exIdParameter, expertIdParameter, coIdParameter, descriptionParameter);
        }
    
        public virtual int sp_tbl_S07_Schedulers_DELETE(Nullable<System.Guid> scId)
        {
            var scIdParameter = scId.HasValue ?
                new ObjectParameter("ScId", scId) :
                new ObjectParameter("ScId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_S07_Schedulers_DELETE", scIdParameter);
        }
    
        public virtual ObjectResult<sp_tbl_S07_Schedulers_GetAll_Result> sp_tbl_S07_Schedulers_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tbl_S07_Schedulers_GetAll_Result>("sp_tbl_S07_Schedulers_GetAll");
        }
    
        public virtual ObjectResult<sp_tbl_S07_Schedulers_GetByScId_Result> sp_tbl_S07_Schedulers_GetByScId(Nullable<System.Guid> scId)
        {
            var scIdParameter = scId.HasValue ?
                new ObjectParameter("ScId", scId) :
                new ObjectParameter("ScId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tbl_S07_Schedulers_GetByScId_Result>("sp_tbl_S07_Schedulers_GetByScId", scIdParameter);
        }
    
        public virtual int sp_tbl_S07_Schedulers_INSERT(Nullable<System.Guid> scId, Nullable<System.Guid> weId, Nullable<System.Guid> shiftId, Nullable<System.Guid> coId, string description)
        {
            var scIdParameter = scId.HasValue ?
                new ObjectParameter("ScId", scId) :
                new ObjectParameter("ScId", typeof(System.Guid));
    
            var weIdParameter = weId.HasValue ?
                new ObjectParameter("WeId", weId) :
                new ObjectParameter("WeId", typeof(System.Guid));
    
            var shiftIdParameter = shiftId.HasValue ?
                new ObjectParameter("ShiftId", shiftId) :
                new ObjectParameter("ShiftId", typeof(System.Guid));
    
            var coIdParameter = coId.HasValue ?
                new ObjectParameter("CoId", coId) :
                new ObjectParameter("CoId", typeof(System.Guid));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_S07_Schedulers_INSERT", scIdParameter, weIdParameter, shiftIdParameter, coIdParameter, descriptionParameter);
        }
    
        public virtual int sp_tbl_S07_Schedulers_UPDATE(Nullable<System.Guid> scId, Nullable<System.Guid> weId, Nullable<System.Guid> shiftId, Nullable<System.Guid> coId, string description)
        {
            var scIdParameter = scId.HasValue ?
                new ObjectParameter("ScId", scId) :
                new ObjectParameter("ScId", typeof(System.Guid));
    
            var weIdParameter = weId.HasValue ?
                new ObjectParameter("WeId", weId) :
                new ObjectParameter("WeId", typeof(System.Guid));
    
            var shiftIdParameter = shiftId.HasValue ?
                new ObjectParameter("ShiftId", shiftId) :
                new ObjectParameter("ShiftId", typeof(System.Guid));
    
            var coIdParameter = coId.HasValue ?
                new ObjectParameter("CoId", coId) :
                new ObjectParameter("CoId", typeof(System.Guid));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_S07_Schedulers_UPDATE", scIdParameter, weIdParameter, shiftIdParameter, coIdParameter, descriptionParameter);
        }
    
        public virtual int sp_tbl_S07_ShiftDay_DELETE(Nullable<System.Guid> shiftId)
        {
            var shiftIdParameter = shiftId.HasValue ?
                new ObjectParameter("ShiftId", shiftId) :
                new ObjectParameter("ShiftId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_S07_ShiftDay_DELETE", shiftIdParameter);
        }
    
        public virtual ObjectResult<sp_tbl_S07_ShiftDay_GetAll_Result> sp_tbl_S07_ShiftDay_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tbl_S07_ShiftDay_GetAll_Result>("sp_tbl_S07_ShiftDay_GetAll");
        }
    
        public virtual ObjectResult<sp_tbl_S07_ShiftDay_GetByShiftId_Result> sp_tbl_S07_ShiftDay_GetByShiftId(Nullable<System.Guid> shiftId)
        {
            var shiftIdParameter = shiftId.HasValue ?
                new ObjectParameter("ShiftId", shiftId) :
                new ObjectParameter("ShiftId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tbl_S07_ShiftDay_GetByShiftId_Result>("sp_tbl_S07_ShiftDay_GetByShiftId", shiftIdParameter);
        }
    
        public virtual int sp_tbl_S07_ShiftDay_INSERT(Nullable<System.Guid> shiftId, string shiftName, string description)
        {
            var shiftIdParameter = shiftId.HasValue ?
                new ObjectParameter("ShiftId", shiftId) :
                new ObjectParameter("ShiftId", typeof(System.Guid));
    
            var shiftNameParameter = shiftName != null ?
                new ObjectParameter("ShiftName", shiftName) :
                new ObjectParameter("ShiftName", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_S07_ShiftDay_INSERT", shiftIdParameter, shiftNameParameter, descriptionParameter);
        }
    
        public virtual int sp_tbl_S07_ShiftDay_UPDATE(Nullable<System.Guid> shiftId, string shiftName, string description)
        {
            var shiftIdParameter = shiftId.HasValue ?
                new ObjectParameter("ShiftId", shiftId) :
                new ObjectParameter("ShiftId", typeof(System.Guid));
    
            var shiftNameParameter = shiftName != null ?
                new ObjectParameter("ShiftName", shiftName) :
                new ObjectParameter("ShiftName", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_S07_ShiftDay_UPDATE", shiftIdParameter, shiftNameParameter, descriptionParameter);
        }
    
        public virtual int sp_tbl_S07_Student_DELETE(Nullable<System.Guid> studetId)
        {
            var studetIdParameter = studetId.HasValue ?
                new ObjectParameter("StudetId", studetId) :
                new ObjectParameter("StudetId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_S07_Student_DELETE", studetIdParameter);
        }
    
        public virtual ObjectResult<sp_tbl_S07_Student_GetAll_Result> sp_tbl_S07_Student_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tbl_S07_Student_GetAll_Result>("sp_tbl_S07_Student_GetAll");
        }
    
        public virtual ObjectResult<sp_tbl_S07_Student_GetByStudetId_Result> sp_tbl_S07_Student_GetByStudetId(Nullable<System.Guid> studetId)
        {
            var studetIdParameter = studetId.HasValue ?
                new ObjectParameter("StudetId", studetId) :
                new ObjectParameter("StudetId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tbl_S07_Student_GetByStudetId_Result>("sp_tbl_S07_Student_GetByStudetId", studetIdParameter);
        }
    
        public virtual int sp_tbl_S07_Student_INSERT(Nullable<System.Guid> studetId, string fullName, string email, string mobile, string address, Nullable<bool> status, Nullable<bool> deleted)
        {
            var studetIdParameter = studetId.HasValue ?
                new ObjectParameter("StudetId", studetId) :
                new ObjectParameter("StudetId", typeof(System.Guid));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("Mobile", mobile) :
                new ObjectParameter("Mobile", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            var deletedParameter = deleted.HasValue ?
                new ObjectParameter("Deleted", deleted) :
                new ObjectParameter("Deleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_S07_Student_INSERT", studetIdParameter, fullNameParameter, emailParameter, mobileParameter, addressParameter, statusParameter, deletedParameter);
        }
    
        public virtual int sp_tbl_S07_Student_UPDATE(Nullable<System.Guid> studetId, string fullName, string email, string mobile, string address, Nullable<bool> status, Nullable<bool> deleted)
        {
            var studetIdParameter = studetId.HasValue ?
                new ObjectParameter("StudetId", studetId) :
                new ObjectParameter("StudetId", typeof(System.Guid));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("Mobile", mobile) :
                new ObjectParameter("Mobile", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            var deletedParameter = deleted.HasValue ?
                new ObjectParameter("Deleted", deleted) :
                new ObjectParameter("Deleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_S07_Student_UPDATE", studetIdParameter, fullNameParameter, emailParameter, mobileParameter, addressParameter, statusParameter, deletedParameter);
        }
    
        public virtual int sp_tbl_S07_StudentDetailt_DELETE(Nullable<System.Guid> stdId)
        {
            var stdIdParameter = stdId.HasValue ?
                new ObjectParameter("StdId", stdId) :
                new ObjectParameter("StdId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_S07_StudentDetailt_DELETE", stdIdParameter);
        }
    
        public virtual ObjectResult<sp_tbl_S07_StudentDetailt_GetAll_Result> sp_tbl_S07_StudentDetailt_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tbl_S07_StudentDetailt_GetAll_Result>("sp_tbl_S07_StudentDetailt_GetAll");
        }
    
        public virtual ObjectResult<sp_tbl_S07_StudentDetailt_GetByStdId_Result> sp_tbl_S07_StudentDetailt_GetByStdId(Nullable<System.Guid> stdId)
        {
            var stdIdParameter = stdId.HasValue ?
                new ObjectParameter("StdId", stdId) :
                new ObjectParameter("StdId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tbl_S07_StudentDetailt_GetByStdId_Result>("sp_tbl_S07_StudentDetailt_GetByStdId", stdIdParameter);
        }
    
        public virtual int sp_tbl_S07_StudentDetailt_INSERT(Nullable<System.Guid> stdId, Nullable<System.Guid> studetId, Nullable<System.Guid> coId, string description)
        {
            var stdIdParameter = stdId.HasValue ?
                new ObjectParameter("StdId", stdId) :
                new ObjectParameter("StdId", typeof(System.Guid));
    
            var studetIdParameter = studetId.HasValue ?
                new ObjectParameter("StudetId", studetId) :
                new ObjectParameter("StudetId", typeof(System.Guid));
    
            var coIdParameter = coId.HasValue ?
                new ObjectParameter("CoId", coId) :
                new ObjectParameter("CoId", typeof(System.Guid));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_S07_StudentDetailt_INSERT", stdIdParameter, studetIdParameter, coIdParameter, descriptionParameter);
        }
    
        public virtual int sp_tbl_S07_StudentDetailt_UPDATE(Nullable<System.Guid> stdId, Nullable<System.Guid> studetId, Nullable<System.Guid> coId, string description)
        {
            var stdIdParameter = stdId.HasValue ?
                new ObjectParameter("StdId", stdId) :
                new ObjectParameter("StdId", typeof(System.Guid));
    
            var studetIdParameter = studetId.HasValue ?
                new ObjectParameter("StudetId", studetId) :
                new ObjectParameter("StudetId", typeof(System.Guid));
    
            var coIdParameter = coId.HasValue ?
                new ObjectParameter("CoId", coId) :
                new ObjectParameter("CoId", typeof(System.Guid));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_S07_StudentDetailt_UPDATE", stdIdParameter, studetIdParameter, coIdParameter, descriptionParameter);
        }
    
        public virtual int sp_tbl_S07_Weekdays_DELETE(Nullable<System.Guid> weId)
        {
            var weIdParameter = weId.HasValue ?
                new ObjectParameter("WeId", weId) :
                new ObjectParameter("WeId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_S07_Weekdays_DELETE", weIdParameter);
        }
    
        public virtual ObjectResult<sp_tbl_S07_Weekdays_GetAll_Result> sp_tbl_S07_Weekdays_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tbl_S07_Weekdays_GetAll_Result>("sp_tbl_S07_Weekdays_GetAll");
        }
    
        public virtual ObjectResult<sp_tbl_S07_Weekdays_GetByWeId_Result> sp_tbl_S07_Weekdays_GetByWeId(Nullable<System.Guid> weId)
        {
            var weIdParameter = weId.HasValue ?
                new ObjectParameter("WeId", weId) :
                new ObjectParameter("WeId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tbl_S07_Weekdays_GetByWeId_Result>("sp_tbl_S07_Weekdays_GetByWeId", weIdParameter);
        }
    
        public virtual int sp_tbl_S07_Weekdays_INSERT(Nullable<System.Guid> weId, string weName, string description)
        {
            var weIdParameter = weId.HasValue ?
                new ObjectParameter("WeId", weId) :
                new ObjectParameter("WeId", typeof(System.Guid));
    
            var weNameParameter = weName != null ?
                new ObjectParameter("WeName", weName) :
                new ObjectParameter("WeName", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_S07_Weekdays_INSERT", weIdParameter, weNameParameter, descriptionParameter);
        }
    
        public virtual int sp_tbl_S07_Weekdays_UPDATE(Nullable<System.Guid> weId, string weName, string description)
        {
            var weIdParameter = weId.HasValue ?
                new ObjectParameter("WeId", weId) :
                new ObjectParameter("WeId", typeof(System.Guid));
    
            var weNameParameter = weName != null ?
                new ObjectParameter("WeName", weName) :
                new ObjectParameter("WeName", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbl_S07_Weekdays_UPDATE", weIdParameter, weNameParameter, descriptionParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<WEB_QLGD01_sp_Account_GetJoin_Result> WEB_QLGD01_sp_Account_GetJoin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_QLGD01_sp_Account_GetJoin_Result>("WEB_QLGD01_sp_Account_GetJoin");
        }
    
        public virtual ObjectResult<WEB_QLGD01_sp_Permission_GetJoin_Result> WEB_QLGD01_sp_Permission_GetJoin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_QLGD01_sp_Permission_GetJoin_Result>("WEB_QLGD01_sp_Permission_GetJoin");
        }
    }
}
