//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_S07_CoursesJournal
    {
        public tbl_S07_CoursesJournal()
        {
            this.tbl_S07_CoursesStudentDetailt = new HashSet<tbl_S07_CoursesStudentDetailt>();
        }
    
        public System.Guid CJId { get; set; }
        public Nullable<System.Guid> CoId { get; set; }
        public Nullable<System.DateTime> DayOf { get; set; }
        public string Contents { get; set; }
        public string Description { get; set; }
    
        public virtual tbl_S07_Courses tbl_S07_Courses { get; set; }
        public virtual ICollection<tbl_S07_CoursesStudentDetailt> tbl_S07_CoursesStudentDetailt { get; set; }
    }
}
