//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FeaId
    {
        public tbl_FeaId()
        {
            this.tbl_Permisstion = new HashSet<tbl_Permisstion>();
        }
    
        public string FeaId { get; set; }
        public string FeaName { get; set; }
        public Nullable<bool> Isdeleted { get; set; }
    
        public virtual ICollection<tbl_Permisstion> tbl_Permisstion { get; set; }
    }
}
