//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Permisstion
    {
        public System.Guid PerID { get; set; }
        public Nullable<bool> F_ADD { get; set; }
        public Nullable<bool> F_EDIT { get; set; }
        public Nullable<bool> F_DELETE { get; set; }
        public Nullable<bool> F_SEARCH { get; set; }
        public string FeaId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
    
        public virtual tbl_Account tbl_Account { get; set; }
        public virtual tbl_FeaId tbl_FeaId { get; set; }
    }
}
