//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_S07_Courses
    {
        public tbl_S07_Courses()
        {
            this.tbl_S07_ExpertsDetailt = new HashSet<tbl_S07_ExpertsDetailt>();
            this.tbl_S07_StudentDetailt = new HashSet<tbl_S07_StudentDetailt>();
            this.tbl_S07_CoursesJournal = new HashSet<tbl_S07_CoursesJournal>();
            this.tbl_S07_Schedulers = new HashSet<tbl_S07_Schedulers>();
        }
    
        public System.Guid CoId { get; set; }
        public string CourseId { get; set; }
        public string CourseName { get; set; }
        public Nullable<byte> TotalNumber { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual ICollection<tbl_S07_ExpertsDetailt> tbl_S07_ExpertsDetailt { get; set; }
        public virtual ICollection<tbl_S07_StudentDetailt> tbl_S07_StudentDetailt { get; set; }
        public virtual ICollection<tbl_S07_CoursesJournal> tbl_S07_CoursesJournal { get; set; }
        public virtual ICollection<tbl_S07_Schedulers> tbl_S07_Schedulers { get; set; }
    }
}
